
def print_error(reason):
    print("Error: " + reason)

